Universe        = vanilla
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 2000M
request_disk    = 2000M
request_cpus    = 1
Priority        = 4
GetEnv          = True
Input           = /star/u/kabir/GIT/BrightSTAR/starSim/lhapdf
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
+Experiment     = "star"
+Job_Type       = "cas"
#transfer_input_files = /star/u/kabir/GIT/BrightSTAR/.sl73_gcc485, /star/u/kabir/GIT/BrightSTAR/lib, /star/u/kabir/GIT/BrightSTAR/rootlogon.C
Executable      = /star/u/kabir/GIT/eicSimUCR/simJobs/condor.sh
Initialdir      = /star/u/kabir/GIT/BrightSTAR/scratch/condor/
Output          = /star/u/kabir/GIT/BrightSTAR/jobOutput/eicDiffJetPro$(Process).out
Error           = /star/u/kabir/GIT/BrightSTAR/jobOutput/eicDiffJetPro$(Process).err
Log             = /star/u/kabir/GIT/BrightSTAR/jobOutput/eicDiffJetPro$(Process).log

Arguments       = $(Process) 50 	
Queue 2

